# Generated by Django 4.2.4 on 2023-10-11 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_customercontact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customercontact',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RemoveField(
            model_name='customercontact',
            name='status',
        ),
        migrations.AddField(
            model_name='customercontact',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customercontact',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customercontact',
            name='phone_number',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
