# Generated by Django 4.2.4 on 2023-10-12 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='contact',
        ),
    ]
