# Generated by Django 4.2.4 on 2023-10-17 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0002_remove_ticket_contact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='status',
            field=models.CharField(choices=[('Open', 'Open'), ('Closed', 'Closed')], default='Open', max_length=10),
        ),
    ]
