# Generated by Django 4.2.4 on 2023-10-11 12:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_customercontact'),
        ('Tickets', '0002_alter_ticket_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Application.customercontact'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], default='Two', max_length=10),
        ),
    ]
