# Generated by Django 4.2.4 on 2023-10-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tickets', '0003_ticket_contact_ticket_priority'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='ticket',
            new_name='belongs_to_ticket',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.CharField(choices=[('one', 'One'), ('two', 'Two'), ('three', 'Three')], default='two', max_length=10),
        ),
    ]
